### ISSUE TITLE
Wrong card sizes in image-dumper (cracker.py)

### ISSUE THREAD

**Issue by maehw** [AeroX2/brother-cart-emulator#6]
Hi @AeroX2 ,

I am still analyzing the CardIO.dll in more detail then before.

Either I am getting something completely wrong or "our" card sizes have been wrong from the beginning.

In your screenshot we see a code snippet: https://raw.githubusercontent.com/AeroX2/brother-cart-emulator/refs/heads/main/image-dumper/images/reverse6.png

I've seen these three values references by: 0x80000, 0x100000, 0x200000 -- and I think those are sizes in bytes (they are also used for dynamic memory allocations with the `new` operator).. and they should translate to 512 kiBytes, 1024 kiBytes and 2048 kiBytes. I don't know why you initially came up with 64 kiBytes... which I think I doubled and quadrupled without further checking (some division by 8 must have happened, but I am pretty sure that the given values are not number of **bits** but number of **bytes**).

I'd be happy if you could confirm. I am then willing to fix cracker.py and provide a MR.

Cheers

**Comment by maehw** [comment]
MR is #7

**Comment by AeroX2** [comment]
>(some division by 8 must have happened, but I am pretty sure that the given values are not number of bits but number of bytes).

Yeah must have. 

I suspect I was just thinking about the chip I was debugging at the time which was a 4 million bit chip which translates to 500Kb and must have just assumed that those numbers were bits rather than bytes.
